version: "3"

services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    container_name: dserver
    # Tell docker what file to build the server from
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    # The ports to expose
    expose:
      - 3001
    # Environment variables
    environment:
      - MONGO_URI=mongodb://db:27017/db
      - PORT=3001
      - DEBUG=worker:*
      - HOST=http://localhost
      - PORT=3000
      - MORGAN=combined
      - NODE_ENV=development
      - TZ=Asia/Kolkata
    # Port mapping
    ports:
      - 3001:3001
    # Volumes to mount
    volumes:
      - ./server:/app/server
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "1"
    # Run command
    # Nodemon for hot reloading (-L flag required for polling in Docker)
    command: nodemon -L ./server.js
    # Connect to other containers
    depends_on:
      - db
    # Restart action
    restart: on-failure
  ##########################
  ### SETUP CLIENT CONTAINER
  ##########################
  client:
    container_name: dclient
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    environment:
      - REACT_APP_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    depends_on:
      - server
    command: npm run start
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "1"

  ##########################
  ### SETUP DB CONTAINER
  ##########################
  db:
    container_name: dmongo
    image: mongo
    ports:
      - 27017:27017
    restart: on-failure
    # uncomment the following three lines to set username and password for mongodb
#   environment:
#     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - devboard-dbdata:/data/db

volumes:
  devboard-dbdata:
