version: "3"

services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    image: backend #change image name here
    container_name: pserver
    environment:
      - MONGO_URI=mongodb://db:27017/db
      - PORT=3001
      - NODE_ENV=production
      - HOST=http://159.65.137.16 # give production url here else, cors won't work
      - TZ=Asia/Kolkata
    command: node server.js
    ports:
      - 80:3001
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    networks:
      - pnetwork

  ##########################
  ### SETUP DB CONTAINER
  ##########################
  db:
    container_name: nbmongo
    image: mongo
    restart: always
    volumes:
      - board-dbdata:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    networks:
      - pnetwork

volumes:
  board-dbdata:

networks:
  pnetwork:
