# Taken from documentation of puppeteer
FROM node:10.9.0-alpine

RUN npm install -g nodemon
RUN mkdir -p /app/server
WORKDIR /app/server
COPY package.*json /app/server/

RUN npm install
copy . /app/server/


CMD ["nodemon"," server.js"]